"""Add created_at and updated_at to Todo

Revision ID: 5edabdf9ef95
Revises: bf3717d1b4bc
Create Date: 2024-08-20 09:06:29.675014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5edabdf9ef95'
down_revision: Union[str, None] = 'bf3717d1b4bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('created_at', sa.DateTime(), nullable=True))  # Adiciona sem valor padrão
    op.add_column('todos', sa.Column('updated_at', sa.DateTime(), nullable=True))  # Adiciona sem valor padrão
    # ### end Alembic commands ###
    # ### end Alembic commands ###
    
    op.execute('UPDATE todos SET created_at = datetime("now"), updated_at = datetime("now")')
    
    op.execute("""
    CREATE TRIGGER update_todos_updated_at
    AFTER UPDATE ON todos
    FOR EACH ROW
    BEGIN
        UPDATE todos SET updated_at = datetime('now') WHERE id = OLD.id;
    END;
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'updated_at')
    op.drop_column('todos', 'created_at')
    # ### end Alembic commands ###

    # Remover o trigger
    op.execute("DROP TRIGGER IF EXISTS update_todos_updated_at;")
